(define (problem wumpus-classical-instance)
  (:domain wumpus-classical)
  (:objects s11 s21 s22 - location)
  (:init
    (at s11)
    (safe s11)
    (safe s21)
    (safe s22)
    (adjacent s11 s21)
    (adjacent s21 s11)
    (adjacent s21 s22)
    (adjacent s22 s21)
    (gold-at s22))
  (:goal (and (have-gold) (at s11) (climbed-out)))
)
